language: node_js
node_js:
  - lts/*
install:
  - yarn install --immutable --immutable-cache --check-cache
script:
  - yarn build
deploy:
  provider: pages
  cleanup: false
  local_dir: dist
  # A token generated on GitHub allowing Travis to push code on you repository.
  # Set in the Travis settings page of your repository, as a secure variable.
  github_token: $GITHUB_TOKEN
  keep_history: false
  target_branch: gh-pages
  on:
    branch: main
cache: yarn